:project:
  :build_root: build
  :release_build: FALSE
  :use_exceptions: TRUE
  :use_mocks: TRUE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :verbosity: 3
:paths:
  :test:
    - test/**
  :source:
    - src/**

:plugins:
  :base_path: ceedling/plugins
  :enabled:
    - stdout_colour_tests_report 

:cmock:
  :mock_prefix: mock_

:unity:
  :defines:
    - UNITY_INT_WIDTH=32 
    - UNITY_EXCLUDE_FLOAT   # no floating point unit
         
